# -*- coding: utf-8 -*-
"""CommonElements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHd8F6i6dK0gbUFPDD3JMqJuVcakJG6p
"""

def common_elements(list1, list2):
  commonElements = set()
  for x in list1:
    for i in list2:
      if i == x:
        commonElements.add(x)
  return commonElements

list = (1, 2, 3, 4, 5, 6)
list2 = (1, 6, 7, 8, 9, 4)
common_elements(list, list2)